# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Maven
on: 
  push:
    branches-ignore:
     - documentation
  pull_request:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Check Maven version
      run: ./mvnw -version
    
    - name: Cleanup testcase parts from library
      run: |
         rm ./plugin.xml
         mv ./replacement_plugin.xml ./plugin.xml
      
    - name: Build with Maven
      run: ./mvnw clean verify
      
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: target-jars
        path: |
            target/**/*.jar
