# This workflow will release to maven central with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Release with Maven
on:
  workflow_dispatch:
    inputs:
      milestone-number:
        description: Milestone number for release(s)
        required: true

jobs:
  release:
    name: Create release and publish to maven central
    runs-on: ubuntu-latest
    environment: Release
    
    steps:
    - uses: actions/checkout@v2
      with:
         ref: master
    - name: Set up JDK 11 # necessary to run tycho 2.5.0
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Check Maven version
      run: ./mvnw -version
              
    - name: Iniitalze and calculate release version by MAVEN
      run: |
        echo "RELEASE_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Package with Maven
      run: ./mvnw -B package --file pom.xml

    - name: Set up Apache Maven Central
      uses: actions/setup-java@v1
      with: # running setup-java again overwrites the settings.xml
        java-version: 11
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}  # Value of the GPG private key to import
        gpg-passphrase:  MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    #- name: Debug output
    #  run: cat ~/.m2/settings.xml

    - name: Publish to Apache Maven Central
      #run: mvn deploy # deploy to staging, so not closing, and can be dropped via Web UI
      run: ./mvnw deploy -P release #deploys and closes release on OSSRH. So not longer staging, cannot be deleted
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}  
      
    - name: "Create release"
      id: "create_release"
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: v${{ env.RELEASE_VERSION }}
          commitish: master
          release_name: Version ${{ env.RELEASE_VERSION }}
          body: |
            Changes in this version
            - Some minor changes and bugfixes
            
            For more details please look at [Milestone ${{github.event.inputs.milestone-number}}]( https://github.com/de-jcup/eclipse-commons/milestone/${{github.event.inputs.milestone-number}}?closed=1)
            
            Artifact can be found at https://mvnrepository.com/artifact/de.jcup.eclipse.commons/eclipse-commons/${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
    